"""Code generation: MyLang AST -> Python source.

The generated module imports ``mylang.runtime.Matrix`` so matrix methods behave
exactly as they do in the interpreter, and it prints booleans as ``#t``/``#f``
through a small ``_print`` helper. Semantics mirror ``interpreter.py``:
integer division is ``//`` and every ``let`` binds an immutable name.

Scoping is preserved by renaming: MyLang lets an inner block shadow an outer
name and forget the shadow when the block ends, which a flat Python function
would not do. Every ``let`` therefore gets a fresh Python name and lookups
resolve through a scope stack, so ``let a = 1; if (#t) { let a = 2; } print(a);``
still prints 1.
"""

from .ast import (
    Program,
    IntegerLiteral,
    StringLiteral,
    BooleanLiteral,
    MatrixLiteral,
    Identifier,
    BinaryExpression,
    UnaryExpression,
    CallExpression,
    MemberCallExpression,
    LetStatement,
    IfStatement,
    WhileStatement,
    PrintStatement,
    ExpressionStatement,
    Block,
)


class CodegenError(Exception):
    pass


_METHODS = {
    "Transpose": "transpose",
    "Reduce": "reduce",
    "isInvertible": "is_invertible",
    "hasNull": "has_null",
}

_HEADER = """\
# Generated by mylang.codegen. Do not edit.
from mylang.runtime import Matrix


def _print(value):
    if value is True:
        print("#t")
    elif value is False:
        print("#f")
    else:
        print(value)


def main():
"""

_FOOTER = """

if __name__ == "__main__":
    main()
"""


class PythonCodegen:
    def __init__(self):
        self.lines = []
        self.indent = 1
        self.scopes = [{}]
        self.counter = 0

    # ----- public -------------------------------------------------------

    def generate(self, program):
        if not isinstance(program, Program):
            raise CodegenError("generate() expects a Program")
        self.lines = []
        self.indent = 1
        self.scopes = [{}]
        self.counter = 0
        if not program.statements:
            self.line("pass")
        for statement in program.statements:
            self.statement(statement)
        return _HEADER + "\n".join(self.lines) + _FOOTER

    # ----- helpers ------------------------------------------------------

    def line(self, text):
        self.lines.append("    " * self.indent + text)

    def declare(self, name):
        self.counter += 1
        python_name = f"{name}_{self.counter}"
        self.scopes[-1][name] = python_name
        return python_name

    def lookup(self, name, node):
        for scope in reversed(self.scopes):
            if name in scope:
                return scope[name]
        raise CodegenError(f"Undefined variable '{name}' at line {node.line}")

    def scoped(self, statements):
        """Emit statements in a fresh MyLang scope; Python needs at least one line."""
        self.scopes.append({})
        self.indent += 1
        if statements:
            for statement in statements:
                self.statement(statement)
        else:
            self.line("pass")
        self.indent -= 1
        self.scopes.pop()

    # ----- statements ---------------------------------------------------

    def statement(self, node):
        method = getattr(self, f"stmt_{type(node).__name__}", None)
        if method is None:
            raise CodegenError(f"No code generation for {type(node).__name__}")
        method(node)

    def stmt_LetStatement(self, node):
        value = self.expression(node.expression)
        self.line(f"{self.declare(node.name)} = {value}")

    def stmt_PrintStatement(self, node):
        self.line(f"_print({self.expression(node.expression)})")

    def stmt_ExpressionStatement(self, node):
        self.line(self.expression(node.expression))

    def stmt_Block(self, node):
        # A bare block: Python has no block scope, so emit `if True:` to keep
        # the statements grouped and use the scope stack for shadowing.
        self.line("if True:")
        self.scoped(node.statements)

    def stmt_IfStatement(self, node):
        self.line(f"if {self.expression(node.condition)}:")
        self.scoped(self.block_statements(node.then_branch))
        if node.else_branch is not None:
            self.line("else:")
            if isinstance(node.else_branch, IfStatement):
                self.scoped([node.else_branch])
            else:
                self.scoped(self.block_statements(node.else_branch))

    def stmt_WhileStatement(self, node):
        self.line(f"while {self.expression(node.condition)}:")
        self.scoped(self.block_statements(node.body))

    @staticmethod
    def block_statements(node):
        return node.statements if isinstance(node, Block) else [node]

    # ----- expressions --------------------------------------------------

    def expression(self, node):
        method = getattr(self, f"expr_{type(node).__name__}", None)
        if method is None:
            raise CodegenError(f"No code generation for {type(node).__name__}")
        return method(node)

    def expr_IntegerLiteral(self, node):
        return repr(node.value)

    def expr_StringLiteral(self, node):
        return repr(node.value)

    def expr_BooleanLiteral(self, node):
        return "True" if node.value else "False"

    def expr_MatrixLiteral(self, node):
        rows = ", ".join("[" + ", ".join(self.expression(e) for e in row) + "]" for row in node.rows)
        return f"Matrix([{rows}])"

    def expr_Identifier(self, node):
        return self.lookup(node.name, node)

    def expr_BinaryExpression(self, node):
        if node.operator == "=":
            raise CodegenError(f"Cannot assign to immutable variable at line {node.line}")
        left = self.expression(node.left)
        right = self.expression(node.right)
        operator = "//" if node.operator == "/" else node.operator
        return f"({left} {operator} {right})"

    def expr_UnaryExpression(self, node):
        if node.operator != "-":
            raise CodegenError(f"Unknown unary operator {node.operator} at line {node.line}")
        return f"(-{self.expression(node.right)})"

    def expr_MemberCallExpression(self, node):
        method = _METHODS.get(node.method)
        if method is None:
            raise CodegenError(f"Unknown matrix method '{node.method}' at line {node.line}")
        if node.arguments:
            raise CodegenError(f"Matrix method '{node.method}' takes no arguments at line {node.line}")
        return f"{self.expression(node.object)}.{method}()"

    def expr_CallExpression(self, node):
        raise CodegenError(f"User defined functions not supported yet at line {node.line}")


def generate_python(program):
    """Convenience wrapper: Program -> Python source text."""
    return PythonCodegen().generate(program)
